import Head from 'next/head'
import Image from 'next/image'
import Input from '../components/Input'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Input />
        <p className="font-bold">words should be displayed here</p>
      </main>
    </div>
  )
}
